package:
  name: ampliconclassifier
  version: 0.4.14

source:
  url: https://github.com/jluebeck/ampliconclassifier/archive/413d6ea936607af68aa8d376074ac18333b3a2e0.tar.gz
  sha256: '279e204eef397ec8204dfe7dce6eae796e7764eae72622a9a42e3df79fb4bec3'

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >=3.7
    - intervaltree
    - matplotlib-base
    - pandas
    - scipy

test:
  commands:
    - amplicon_classifier.py --help
    - amplicon_similarity.py --help
    - amplicons_intersecting_bed.py --help
    - make_results_table.py --help

about:
  home: https://github.com/jluebeck/AmpliconClassifier
  summary: |
          AmpliconClassifier classifies the output of AmpliconArchitect to detect different types of focal amplifications.
  dev_url: https://github.com/jluebeck/AmpliconClassifier
  license_family: BSD
  license: BSD 2-Clause
