{% set name = "perl-html-parser" %}
{% set version = "3.77" %}
{% set sha256 = "792a6e314f8eb0e87be7f5fdcf1b0c170a26a0e53da48d9a315db76f876949f3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.77.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-extutils-makemaker
    - perl-html-tagset
    - perl-test-simple
    - perl-uri
  run:
    - perl
    - perl-html-tagset
    - perl-uri

test:
  imports:
    - HTML::Filter
    - HTML::Parser

about:
  home: http://metacpan.org/pod/HTML::Parser
  license: perl_5
  summary: 'HTML parser class'
