{% set name = "GraphAligner" %}
{% set version = "1.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maickrau/{{ name }}/files/8334258/{{ name }}.tar.gz
  sha256: b53886d8e6fcadb22a164b0a509278d0c30d7b7e9fd2f6aba13070805a93c2a4
  patches: version.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - jemalloc=5.2.0
    - zlib
    - boost=1.67.0
    - libboost=1.67.0
    - sparsehash
    - pkg-config
    - libdivsufsort
    - protobuf=3.14.0
    - libprotobuf-static=3.14.0
    - sdsl-lite

test:
  commands:
    - (GraphAligner -h || true) | grep GraphAligner

about:
  home: https://github.com/maickrau/GraphAligner
  license: MIT
  license_file: LICENSE.md
  summary: Sequence to graph aligner for long reads
  identifier: https://doi.org/10.1101/323063
